version: 0.2

env:
  variables:
    S3_BUCKET: cargocom-claim-source
    LAYER_ZIP: claim/layer.zip
    LAYER_NAME: cargocom-mail-layer

phases:
  install:
    commands:
      - mkdir -p layer/nodejs
      - cd layer/nodejs
      - npm init -y
      - npm install googleapis nodemailer
      - cd ..
      - zip -r layer.zip nodejs

  post_build:
    commands:
      - echo "☁️ Subiendo layer a S3.."
      - aws s3 cp layer.zip s3://$S3_BUCKET/$LAYER_ZIP
      - echo "🚀 Publicando layer en Lambda..."
      - aws lambda publish-layer-version \
          --layer-name $LAYER_NAME \
          --content S3Bucket=$S3_BUCKET,S3Key=$LAYER_ZIP \
          --compatible-runtimes nodejs18.x
